-- Schema v10: dashboard history read model & kb_max_documents.
-- knowledge_bases.max_documents adds configurable document limit (default 100).
-- Existing message-bearing threads are backfilled lazily; new/empty threads can use
-- the projection immediately.

ALTER TABLE knowledge_bases
  ADD COLUMN IF NOT EXISTS max_documents INTEGER NOT NULL DEFAULT 100;

CREATE TABLE IF NOT EXISTS thread_messages (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id     TEXT NOT NULL REFERENCES threads(thread_id) ON DELETE CASCADE,
  seq           BIGINT NOT NULL,
  message_id    TEXT,
  role          TEXT NOT NULL,
  message_json  TEXT NOT NULL,
  created_at    BIGINT NOT NULL,
  UNIQUE(thread_id, seq),
  UNIQUE(thread_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_thread_messages_thread_seq
  ON thread_messages(thread_id, seq DESC);

CREATE TABLE IF NOT EXISTS thread_history_projection (
  thread_id    TEXT PRIMARY KEY REFERENCES threads(thread_id) ON DELETE CASCADE,
  status       TEXT NOT NULL,
  updated_at   BIGINT NOT NULL,
  error        TEXT
);

INSERT INTO thread_history_projection(thread_id, status, updated_at, error)
SELECT thread_id,
       CASE WHEN last_active > 0 OR title IS NOT NULL THEN 'pending' ELSE 'ready' END,
       EXTRACT(EPOCH FROM NOW())::BIGINT,
       NULL
FROM threads
ON CONFLICT(thread_id) DO NOTHING;

UPDATE _schema_version SET version = 10;
